### ISSUE TITLE
Where is the .sln?

### ISSUE THREAD

**Issue by 0xh3LL0** [EusthEnoptEron/RaiLTools#1]
without this, i cant build the project...

**Comment by EusthEnoptEron** [comment]
Added. Does it compile now?

**Comment by 0xh3LL0** [comment]
i got this error, any idea? 
used version visual studio 2017, and sadly i'm not a programmer... :( 

NuGet Package restore failed for project railiar: Unable to find version '1.2.6' of package 'BinaryBitLib'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'BinaryBitLib.1.2.6' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
  An error occurred while sending the request.
  The remote name could not be resolved: 'api.nuget.org'
.
NuGet Package restore failed for project railiar: Unable to find version '1.0.3' of package 'BitStream'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'BitStream.1.0.3' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
  An error occurred while sending the request.
  The remote name could not be resolved: 'api.nuget.org'
.
NuGet Package restore failed for project RaiLTools: Unable to find version '1.0.1' of package 'NHyphenator'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'NHyphenator.1.0.1' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
  An error occurred while sending the request.
  The remote name could not be resolved: 'api.nuget.org'
.
1>------ Build started: Project: RaiLTools, Configuration: Release Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "NHyphenator". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>d:\RaiLTools-master\RailTools\TransFile.cs(1,7,1,18): error CS0246: The type or namespace name 'NHyphenator' could not be found (are you missing a using directive or an assembly reference?)
2>------ Build started: Project: railiar, Configuration: Release Any CPU ------
2>CSC : error CS0006: Metadata file 'd:\RaiLTools-master\RailTools\bin\Release\RaiLTools.dll' could not be found
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

**Comment by EusthEnoptEron** [comment]
Sounds like you can't reach Nuget... Are you behind a proxy or something?

Also, if you just want to use the library, you can download the release: https://github.com/EusthEnoptEron/RaiLTools/releases

**Comment by 0xh3LL0** [comment]
i did want to use your already build tools,  but it seem out to date (2015),  so i tried to build my self and i'm working on non internet environment, (so that make sense for the error, huh... )
or can you rebuild it again and put on the release,  please... :D

**Comment by 0xh3LL0** [comment]
my lord, finally i can build this...
thanks for your tools!
