### ISSUE TITLE
Add support for two games

### ISSUE THREAD

**Issue by Tfausx** [EusthEnoptEron/RaiLTools#2]
Hello! I hope you're having a nice day! I was wondering if it possible to add support for this two games:

https://vndb.org/v16796

https://vndb.org/v20701

Thanks in advance!

**Comment by simon-meer** [comment]
Hey there,

Is there anything specific that does not work?
I did a quick test with Fairytale Requiem and didn't have any issues extracting images, text, and music or changing the text.

**Comment by EusthEnoptEron** [comment]
Hey there,

Is there anything specific that does not work?
I did a quick test with Fairytale Requiem and didn't have any issues extracting images, text, and music or changing the text.

**Comment by Tfausx** [comment]
Hello again, thanks for reply! Yeah, everything extracts fine , but when i use the cmd to transform .gsc to .txt, it give me an empy text or which i show you in the image

https://i.ibb.co/5kYfq0d/Sin-t-tulo.png

I use the command railiar.exe 4000.gsc 4000.txt

Maybe i'm doing something wrong?

Thanks in advance!

**Comment by EusthEnoptEron** [comment]
Some files do not contain any text (presumably) and will yield such txt files. You should be able to safely ignore the strange strings.

e.g. in case of Fairytale Requiem, 000.gsc - 0522.gsc contain no text, 1001.gsc is a test scene, and 1101.gsc is where the prologue starts.

**Comment by Tfausx** [comment]
Thanks for the answer! Now everything have sense and it's fully working! Thanks again for your hard work

Have a nice day!
